### ISSUE TITLE
feature request: polars new datatype Small Strings in polars 0.43.1

### ISSUE THREAD

**Issue by GuillaumePressiat** [jmcnamara/polars_excel_writer#20]
### Feature Request

Hi,

In 0.43.1 polars team have introduced a new datatype for small character strings.

I've tweaked your code to take it into account here:
https://github.com/GuillaumePressiat/polars_excel_writer/commit/4c97463007a742d20f657d00561be9bc70363862

Since you have to first release rust_xlsxwriter with 0.43.1 in Cargo.toml into it and since it's not a minor polars release that may contains side effects I will not make a pull request.
(Existing 32 tests runs fine but I've not made new ones for this new datatype). 

I've used `.into()` somewhere to push str into polars small string but there is certainly a better way.

**Comment by jmcnamara** [comment]
Thanks. I'll look into it.

**Comment by jmcnamara** [comment]
Thanks. I pushed a fix for that to main. It ended up being more or less exactly the same as your suggestions.

If it looks okay to you I'll do a v0.76.1 release of rust_xlsxwriter.

BTW, did you find this just by upgrading to the latest version of Polars?

**Comment by jmcnamara** [comment]
This is now fixed and upstream in v0.9.0 of `polars_excel_writer`

**Comment by GuillaumePressiat** [comment]
> BTW, did you find this just by upgrading to the latest version of Polars?

Sorry for the late answer.
Yes. In a project where both polars and  polars_excel_writer are in cargo.toml. When upgrading to 0.43.1 project didn't build.

Thanks for your work.
